steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f',
        'Dockerfile',
        '-t',
        'gcr.io/$PROJECT_ID/reacjilator',
        '.',
      ]
images:
  - 'gcr.io/$PROJECT_ID/reacjilator'
